config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :home, only: [:index]
  resources :categories, only: %i[index new create]
  resources :invoices, only: %i[index new create], as: :transactions
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  include ImageUploader::Attachment(:icon)

  belongs_to :user
  has_many :records, dependent: :destroy
  has_and_belongs_to_many :invoices, join_table: :records

  validates :name, presence: true
  validates :icon_data, presence: true

  def total_invoices
    total = 0
    invoices.each do |invoice|
      total += invoice.amount
    end
    total
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  has_many :records, dependent: :destroy
  has_and_belongs_to_many :categories, join_table: :records

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :category
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :categories, dependent: :destroy
  has_many :invoices, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to home_index_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(user: current_user)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    @category.icon_derivatives!

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.includes(:invoices).find(params[:format])
    @invoices = @category.invoices.order('created_at DESC')
  end

  def new
    @invoice = Invoice.new
    @categories = Category.where(user: current_user)
  end

  def create
    if record_params[:categories].nil?
      flash[:alert] = 'Please select at least one category'
      redirect_to new_transaction_path
      return
    end

    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user

    if @invoice.save
      category_ids = record_params[:categories].map(&:to_i)
      record_params[:categories].each do |id|
        Record.create(invoice: @invoice, category_id: id)
      end
      flash[:notice] = 'Transaction created successfully'
      redirect_to transactions_path(category_ids.first)
    else
      render :new
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:name, :amount)
  end

  def record_params
    params.require(:invoice).permit(categories: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.haml
.categories.flex.flex-col.items-center.min-h-screen
  .navbar.bg-gradient-to-b.from-blue1.to-blue2.h-24.w-screen.flex.items-center.text-white.justify-center.fixed
    %a{:href => categories_path, :class => "absolute top-12 left-4 text-2xl"} ☰
    %h1.text-2xl.mt-8
      CATEGORIES
    = button_to "[➥", destroy_user_session_path, method: :delete, |
      class: 'absolute top-12 right-3 font-bold text-2xl',        |
      title: 'Log-out'
  .list.w-screen.flex.flex-col.items-center.px-2.pt-28.pb-24
    - if @categories.length > 0
      - @categories.each do |category|
        = link_to transactions_path(category), class: "bg-white rounded p-4 my-2 w-[100%] max-w-[612px] text-center flex items-stretch gap-4" do
          %img{:src => category.icon(:small).url, :class => "w-24 h-24"}
          .info.flex.flex-col.justify-between.w-full
            %h3.text-2xl.font-semibold.text-darker.self-start.cursor-pointer
              = category.name
            %p.self-end
              %span.text-dark
                Total transactions:
              = "$#{category.total_invoices}"
    - else
      %h2.font-semibold.text-3xl
        No Categories Yet
  %div(class="fixed bottom-0 bg-green text-white p-4 w-[100%] max-w-[612px] text-center mt-auto cursor-pointer flex flex-col items-stretch")
    = link_to 'NEW CATEGORY', new_category_path, class: "border border-white rounded bg-green text-white py-4 text-center mt-auto"

app/views/categories/new.html.haml
.new-category.flex.flex-col.items-center.h-screen
  .navbar.bg-gradient-to-b.from-blue1.to-blue2.h-24.w-screen.flex.items-center.text-white.justify-center.relative
    %a{:href => categories_path, :class => "absolute top-10 left-4 text-5xl", :title => "Back"} ←
    %h1.text-2xl.mt-8
      NEW CATEGORY
    = button_to "[➥", destroy_user_session_path, method: :delete, |
      class: 'absolute top-12 right-3 font-bold text-2xl',        |
      title: 'Log-out'
  .form-container
    = form_with model: @category, url: categories_path, method: :post, class: "w-screen max-w-[612px] p-2" do |f|
      .field.my-4
        = f.text_field :name, placeholder: "Name", class: "w-[100%] border-none h-14 px-4 text-darker placeholder:text-light"
      .field.flex.items-center.mb-8.ml-6.gap-2
        = f.label "Icon:", class: "text-darker text-lg"
        = f.file_field :icon
      .actions.text-center
        = f.submit "Create", class: "rounded bg-blue1 text-white py-4 w-[95%] text-center mt-auto cursor-pointer active:scale-95"

app/views/home/index.html.haml
.home-page.h-screen.flex.flex-col.items-center.bg-white
  .logo
    = image_tag "/blue-ray.svg", alt: "Logo", class: "mt-32"
  .buttons(class="mt-auto mb-14 w-[90%] flex flex-col items-center")
    = link_to "LOG IN", new_user_session_path, class: "rounded bg-blue1 text-white py-4 w-[100%] text-center mb-4"
    = link_to "SIGN UP", new_user_registration_path

app/views/invoices/index.html.haml
.transactions(class="flex flex-col items-center min-h-screen w-[100%] max-w-[612px]")
  .navbar.bg-gradient-to-b.from-blue1.to-blue2.h-24.w-screen.flex.items-center.text-white.justify-center.fixed
    %a{:href => categories_path, :class => "absolute top-10 left-4 text-5xl", :title => "Back"} ←
    %h1.text-2xl.mt-8
      = "#{@category.name} Transactions"
    = button_to "[➥", destroy_user_session_path, method: :delete, |
      class: 'absolute top-12 right-3 font-bold text-2xl',        |
      title: 'Log-out'
  .content{class: "w-screen flex flex-col items-center px-2 pt-28 w-[100%] max-w-[612px] pb-24"}
    .total.flex.items-center.self-end.p-2
      %h2.text-xl.text-darker
        Total:
        %span.text-xl.font-light.text-darker
          = "$#{@category.total_invoices}"
    .list.w-screen.flex.flex-col.items-center.p-2
      - if @invoices.length > 0
        - @invoices.each_with_index do |invoice, i|
          .transaction(class="bg-white rounded p-4 my-2 w-[100%] max-w-[612px] flex justify-between gap-4 items-center")
            %h3.text-xl.text-darker.cursor-pointer
              = "#{i + 1}. #{invoice.name}"
            %p
              %span.text-dark
                Amount:
              = "$#{invoice.amount}"
      - else
        %h2.font-semibold.text-3xl
          No Transactions Yet
  %div(class="fixed bottom-0 bg-green text-white p-4 w-[100%] max-w-[612px] text-center mt-auto cursor-pointer flex flex-col items-stretch")
    = link_to 'NEW TRANSACTION', new_transaction_path, class: "border border-white rounded bg-green text-white py-4 text-center mt-auto"

app/views/invoices/new.html.haml
.new-transaction.flex.flex-col.items-center.h-screen
  .navbar.bg-gradient-to-b.from-blue1.to-blue2.h-24.w-screen.flex.items-center.text-white.justify-center.relative
    %a{:href => categories_path, :class => "absolute top-10 left-4 text-5xl", :title => "Back"} ←
    %h1.text-2xl.mt-8
      NEW TRANSACTION
    = button_to "[➥", destroy_user_session_path, method: :delete, |
      class: 'absolute top-12 right-3 font-bold text-2xl',        |
      title: 'Log-out'
  = form_with model: @invoice, url: transactions_path, method: :post, class: "w-screen max-w-[612px] p-2" do |f|
    .field.my-4
      = f.text_field :name, placeholder: "Name", class: "w-[100%] border-none h-14 px-4 text-darker placeholder:text-light"
    .field.mb-4.flex.flex-col.gap-2.ml-4
      = f.label "Category:", class: "text-darker text-xl"
      - if @categories.empty?
        %p You have no categories yet. Please create one first.
      - else
        .check-boxes.flex.flex-col.items-start.gap-2.ml-4.text-lg.text-dark.font-light
          - @categories.each do |category|
            .option.flex.items-center.gap-2
              = f.check_box :categories, { multiple: true }, category.id, nil
              = f.label category.name
    .field.mb-8
      = f.number_field :amount, step: 0.01, placeholder: "Amount", class: "w-[100%] border-none h-14 px-4 text-darker placeholder:text-light"
    .actions.text-center
      = f.submit "Create", class: "rounded bg-blue1 text-white py-4 w-[95%] text-center mt-auto cursor-pointer active:scale-95"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlueRayPay
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %main.flex.flex-col.min-h-screen.items-center.font-p.font-normal.text-medium.bg-gray-100
      - if flash[:notice]
        %p.notice.fixed.top-0.right-0.left-0.bg-green-100.text-green-500.text-center.py-2.z-10
          = notice
      - if flash[:alert]
        %p.alert.fixed.top-0.right-0.left-0.bg-red-100.text-red-500.text-center.py-2.z-10
          = alert
      = yield